// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.github.protoservice.entities.proto;

public final class UserResponse {
  private UserResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.protoservice.entities.proto.UserResponse.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.protoservice.entities.proto.UserResponse.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.protoservice.entities.proto.UserResponse.User.class, com.github.protoservice.entities.proto.UserResponse.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.protoservice.entities.proto.UserResponse.User)) {
        return super.equals(obj);
      }
      com.github.protoservice.entities.proto.UserResponse.User other = (com.github.protoservice.entities.proto.UserResponse.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.protoservice.entities.proto.UserResponse.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.protoservice.entities.proto.UserResponse.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.github.protoservice.entities.proto.UserResponse.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.protoservice.entities.proto.UserResponse.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.protoservice.entities.proto.UserResponse.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.protoservice.entities.proto.UserResponse.User.class, com.github.protoservice.entities.proto.UserResponse.User.Builder.class);
      }

      // Construct using com.github.protoservice.entities.proto.UserResponse.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.protoservice.entities.proto.UserResponse.internal_static_User_descriptor;
      }

      public com.github.protoservice.entities.proto.UserResponse.User getDefaultInstanceForType() {
        return com.github.protoservice.entities.proto.UserResponse.User.getDefaultInstance();
      }

      public com.github.protoservice.entities.proto.UserResponse.User build() {
        com.github.protoservice.entities.proto.UserResponse.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.protoservice.entities.proto.UserResponse.User buildPartial() {
        com.github.protoservice.entities.proto.UserResponse.User result = new com.github.protoservice.entities.proto.UserResponse.User(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.protoservice.entities.proto.UserResponse.User) {
          return mergeFrom((com.github.protoservice.entities.proto.UserResponse.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.protoservice.entities.proto.UserResponse.User other) {
        if (other == com.github.protoservice.entities.proto.UserResponse.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.protoservice.entities.proto.UserResponse.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.protoservice.entities.proto.UserResponse.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.github.protoservice.entities.proto.UserResponse.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.protoservice.entities.proto.UserResponse.User();
    }

    public static com.github.protoservice.entities.proto.UserResponse.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.github.protoservice.entities.proto.UserResponse.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UsersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Users)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    java.util.List<com.github.protoservice.entities.proto.UserResponse.User> 
        getAllUsersList();
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    com.github.protoservice.entities.proto.UserResponse.User getAllUsers(int index);
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    int getAllUsersCount();
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    java.util.List<? extends com.github.protoservice.entities.proto.UserResponse.UserOrBuilder> 
        getAllUsersOrBuilderList();
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    com.github.protoservice.entities.proto.UserResponse.UserOrBuilder getAllUsersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Users}
   */
  public static final class Users extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Users)
      UsersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Users.newBuilder() to construct.
    private Users(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Users() {
      allUsers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Users();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Users(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                allUsers_ = new java.util.ArrayList<com.github.protoservice.entities.proto.UserResponse.User>();
                mutable_bitField0_ |= 0x00000001;
              }
              allUsers_.add(
                  input.readMessage(com.github.protoservice.entities.proto.UserResponse.User.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          allUsers_ = java.util.Collections.unmodifiableList(allUsers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.protoservice.entities.proto.UserResponse.internal_static_Users_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.protoservice.entities.proto.UserResponse.internal_static_Users_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.protoservice.entities.proto.UserResponse.Users.class, com.github.protoservice.entities.proto.UserResponse.Users.Builder.class);
    }

    public static final int ALLUSERS_FIELD_NUMBER = 1;
    private java.util.List<com.github.protoservice.entities.proto.UserResponse.User> allUsers_;
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    public java.util.List<com.github.protoservice.entities.proto.UserResponse.User> getAllUsersList() {
      return allUsers_;
    }
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    public java.util.List<? extends com.github.protoservice.entities.proto.UserResponse.UserOrBuilder> 
        getAllUsersOrBuilderList() {
      return allUsers_;
    }
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    public int getAllUsersCount() {
      return allUsers_.size();
    }
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    public com.github.protoservice.entities.proto.UserResponse.User getAllUsers(int index) {
      return allUsers_.get(index);
    }
    /**
     * <code>repeated .User allUsers = 1;</code>
     */
    public com.github.protoservice.entities.proto.UserResponse.UserOrBuilder getAllUsersOrBuilder(
        int index) {
      return allUsers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allUsers_.size(); i++) {
        output.writeMessage(1, allUsers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allUsers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allUsers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.protoservice.entities.proto.UserResponse.Users)) {
        return super.equals(obj);
      }
      com.github.protoservice.entities.proto.UserResponse.Users other = (com.github.protoservice.entities.proto.UserResponse.Users) obj;

      if (!getAllUsersList()
          .equals(other.getAllUsersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAllUsersCount() > 0) {
        hash = (37 * hash) + ALLUSERS_FIELD_NUMBER;
        hash = (53 * hash) + getAllUsersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.protoservice.entities.proto.UserResponse.Users parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.protoservice.entities.proto.UserResponse.Users prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Users}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Users)
        com.github.protoservice.entities.proto.UserResponse.UsersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.protoservice.entities.proto.UserResponse.internal_static_Users_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.protoservice.entities.proto.UserResponse.internal_static_Users_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.protoservice.entities.proto.UserResponse.Users.class, com.github.protoservice.entities.proto.UserResponse.Users.Builder.class);
      }

      // Construct using com.github.protoservice.entities.proto.UserResponse.Users.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllUsersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (allUsersBuilder_ == null) {
          allUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allUsersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.protoservice.entities.proto.UserResponse.internal_static_Users_descriptor;
      }

      public com.github.protoservice.entities.proto.UserResponse.Users getDefaultInstanceForType() {
        return com.github.protoservice.entities.proto.UserResponse.Users.getDefaultInstance();
      }

      public com.github.protoservice.entities.proto.UserResponse.Users build() {
        com.github.protoservice.entities.proto.UserResponse.Users result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.protoservice.entities.proto.UserResponse.Users buildPartial() {
        com.github.protoservice.entities.proto.UserResponse.Users result = new com.github.protoservice.entities.proto.UserResponse.Users(this);
        int from_bitField0_ = bitField0_;
        if (allUsersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            allUsers_ = java.util.Collections.unmodifiableList(allUsers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allUsers_ = allUsers_;
        } else {
          result.allUsers_ = allUsersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.protoservice.entities.proto.UserResponse.Users) {
          return mergeFrom((com.github.protoservice.entities.proto.UserResponse.Users)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.protoservice.entities.proto.UserResponse.Users other) {
        if (other == com.github.protoservice.entities.proto.UserResponse.Users.getDefaultInstance()) return this;
        if (allUsersBuilder_ == null) {
          if (!other.allUsers_.isEmpty()) {
            if (allUsers_.isEmpty()) {
              allUsers_ = other.allUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllUsersIsMutable();
              allUsers_.addAll(other.allUsers_);
            }
            onChanged();
          }
        } else {
          if (!other.allUsers_.isEmpty()) {
            if (allUsersBuilder_.isEmpty()) {
              allUsersBuilder_.dispose();
              allUsersBuilder_ = null;
              allUsers_ = other.allUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allUsersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllUsersFieldBuilder() : null;
            } else {
              allUsersBuilder_.addAllMessages(other.allUsers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.protoservice.entities.proto.UserResponse.Users parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.protoservice.entities.proto.UserResponse.Users) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.github.protoservice.entities.proto.UserResponse.User> allUsers_ =
        java.util.Collections.emptyList();
      private void ensureAllUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          allUsers_ = new java.util.ArrayList<com.github.protoservice.entities.proto.UserResponse.User>(allUsers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.protoservice.entities.proto.UserResponse.User, com.github.protoservice.entities.proto.UserResponse.User.Builder, com.github.protoservice.entities.proto.UserResponse.UserOrBuilder> allUsersBuilder_;

      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public java.util.List<com.github.protoservice.entities.proto.UserResponse.User> getAllUsersList() {
        if (allUsersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allUsers_);
        } else {
          return allUsersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public int getAllUsersCount() {
        if (allUsersBuilder_ == null) {
          return allUsers_.size();
        } else {
          return allUsersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public com.github.protoservice.entities.proto.UserResponse.User getAllUsers(int index) {
        if (allUsersBuilder_ == null) {
          return allUsers_.get(index);
        } else {
          return allUsersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder setAllUsers(
          int index, com.github.protoservice.entities.proto.UserResponse.User value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.set(index, value);
          onChanged();
        } else {
          allUsersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder setAllUsers(
          int index, com.github.protoservice.entities.proto.UserResponse.User.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.set(index, builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder addAllUsers(com.github.protoservice.entities.proto.UserResponse.User value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.add(value);
          onChanged();
        } else {
          allUsersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder addAllUsers(
          int index, com.github.protoservice.entities.proto.UserResponse.User value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.add(index, value);
          onChanged();
        } else {
          allUsersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder addAllUsers(
          com.github.protoservice.entities.proto.UserResponse.User.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.add(builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder addAllUsers(
          int index, com.github.protoservice.entities.proto.UserResponse.User.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.add(index, builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder addAllAllUsers(
          java.lang.Iterable<? extends com.github.protoservice.entities.proto.UserResponse.User> values) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allUsers_);
          onChanged();
        } else {
          allUsersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder clearAllUsers() {
        if (allUsersBuilder_ == null) {
          allUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allUsersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public Builder removeAllUsers(int index) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.remove(index);
          onChanged();
        } else {
          allUsersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public com.github.protoservice.entities.proto.UserResponse.User.Builder getAllUsersBuilder(
          int index) {
        return getAllUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public com.github.protoservice.entities.proto.UserResponse.UserOrBuilder getAllUsersOrBuilder(
          int index) {
        if (allUsersBuilder_ == null) {
          return allUsers_.get(index);  } else {
          return allUsersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public java.util.List<? extends com.github.protoservice.entities.proto.UserResponse.UserOrBuilder> 
           getAllUsersOrBuilderList() {
        if (allUsersBuilder_ != null) {
          return allUsersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allUsers_);
        }
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public com.github.protoservice.entities.proto.UserResponse.User.Builder addAllUsersBuilder() {
        return getAllUsersFieldBuilder().addBuilder(
            com.github.protoservice.entities.proto.UserResponse.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public com.github.protoservice.entities.proto.UserResponse.User.Builder addAllUsersBuilder(
          int index) {
        return getAllUsersFieldBuilder().addBuilder(
            index, com.github.protoservice.entities.proto.UserResponse.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User allUsers = 1;</code>
       */
      public java.util.List<com.github.protoservice.entities.proto.UserResponse.User.Builder> 
           getAllUsersBuilderList() {
        return getAllUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.protoservice.entities.proto.UserResponse.User, com.github.protoservice.entities.proto.UserResponse.User.Builder, com.github.protoservice.entities.proto.UserResponse.UserOrBuilder> 
          getAllUsersFieldBuilder() {
        if (allUsersBuilder_ == null) {
          allUsersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.protoservice.entities.proto.UserResponse.User, com.github.protoservice.entities.proto.UserResponse.User.Builder, com.github.protoservice.entities.proto.UserResponse.UserOrBuilder>(
                  allUsers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          allUsers_ = null;
        }
        return allUsersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Users)
    }

    // @@protoc_insertion_point(class_scope:Users)
    private static final com.github.protoservice.entities.proto.UserResponse.Users DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.protoservice.entities.proto.UserResponse.Users();
    }

    public static com.github.protoservice.entities.proto.UserResponse.Users getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Users>
        PARSER = new com.google.protobuf.AbstractParser<Users>() {
      public Users parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Users(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Users> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Users> getParserForType() {
      return PARSER;
    }

    public com.github.protoservice.entities.proto.UserResponse.Users getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Users_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Users_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013users.proto\" \n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\" \n\005Users\022\027\n\010allUsers\030\001 \003(\0132\005.Use" +
      "rB6\n&com.github.protoservice.entities.pr" +
      "otoB\014UserResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Users_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Users_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Users_descriptor,
        new java.lang.String[] { "AllUsers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
